<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form1
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim GridViewTextBoxColumn1 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn2 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn3 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn4 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn5 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn6 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn7 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn8 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn9 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn10 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Dim GridViewTextBoxColumn11 As Telerik.WinControls.UI.GridViewTextBoxColumn = New Telerik.WinControls.UI.GridViewTextBoxColumn()
        Me.RadMultiColumnComboBox1 = New Telerik.WinControls.UI.RadMultiColumnComboBox()
        Me.CustomersBindingSource = New System.Windows.Forms.BindingSource(Me.components)
        Me.NwindDataSet = New MCCB_CustomFilteringVB.NwindDataSet()
        Me.CustomersTableAdapter = New MCCB_CustomFilteringVB.NwindDataSetTableAdapters.CustomersTableAdapter()
        CType(Me.RadMultiColumnComboBox1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.RadMultiColumnComboBox1.EditorControl, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.CustomersBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.NwindDataSet, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'RadMultiColumnComboBox1
        '
        Me.RadMultiColumnComboBox1.DataSource = Me.CustomersBindingSource
        Me.RadMultiColumnComboBox1.DisplayMember = "CustomerID"
        '
        'RadMultiColumnComboBox1.NestedRadGridView
        '
        Me.RadMultiColumnComboBox1.EditorControl.BackColor = System.Drawing.SystemColors.Window
        Me.RadMultiColumnComboBox1.EditorControl.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.RadMultiColumnComboBox1.EditorControl.ForeColor = System.Drawing.SystemColors.ControlText
        Me.RadMultiColumnComboBox1.EditorControl.Location = New System.Drawing.Point(0, 0)
        '
        '
        '
        Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate.AllowAddNewRow = False
        Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate.AllowCellContextMenu = False
        Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate.AllowColumnChooser = False
        GridViewTextBoxColumn1.FieldName = "CustomerID"
        GridViewTextBoxColumn1.HeaderText = "CustomerID"
        GridViewTextBoxColumn1.IsAutoGenerated = True
        GridViewTextBoxColumn1.Name = "CustomerID"
        GridViewTextBoxColumn2.FieldName = "CompanyName"
        GridViewTextBoxColumn2.HeaderText = "CompanyName"
        GridViewTextBoxColumn2.IsAutoGenerated = True
        GridViewTextBoxColumn2.Name = "CompanyName"
        GridViewTextBoxColumn3.FieldName = "ContactName"
        GridViewTextBoxColumn3.HeaderText = "ContactName"
        GridViewTextBoxColumn3.IsAutoGenerated = True
        GridViewTextBoxColumn3.Name = "ContactName"
        GridViewTextBoxColumn4.FieldName = "ContactTitle"
        GridViewTextBoxColumn4.HeaderText = "ContactTitle"
        GridViewTextBoxColumn4.IsAutoGenerated = True
        GridViewTextBoxColumn4.Name = "ContactTitle"
        GridViewTextBoxColumn5.FieldName = "Address"
        GridViewTextBoxColumn5.HeaderText = "Address"
        GridViewTextBoxColumn5.IsAutoGenerated = True
        GridViewTextBoxColumn5.Name = "Address"
        GridViewTextBoxColumn6.FieldName = "City"
        GridViewTextBoxColumn6.HeaderText = "City"
        GridViewTextBoxColumn6.IsAutoGenerated = True
        GridViewTextBoxColumn6.Name = "City"
        GridViewTextBoxColumn7.FieldName = "Region"
        GridViewTextBoxColumn7.HeaderText = "Region"
        GridViewTextBoxColumn7.IsAutoGenerated = True
        GridViewTextBoxColumn7.Name = "Region"
        GridViewTextBoxColumn8.FieldName = "PostalCode"
        GridViewTextBoxColumn8.HeaderText = "PostalCode"
        GridViewTextBoxColumn8.IsAutoGenerated = True
        GridViewTextBoxColumn8.Name = "PostalCode"
        GridViewTextBoxColumn9.FieldName = "Country"
        GridViewTextBoxColumn9.HeaderText = "Country"
        GridViewTextBoxColumn9.IsAutoGenerated = True
        GridViewTextBoxColumn9.Name = "Country"
        GridViewTextBoxColumn10.FieldName = "Phone"
        GridViewTextBoxColumn10.HeaderText = "Phone"
        GridViewTextBoxColumn10.IsAutoGenerated = True
        GridViewTextBoxColumn10.Name = "Phone"
        GridViewTextBoxColumn11.FieldName = "Fax"
        GridViewTextBoxColumn11.HeaderText = "Fax"
        GridViewTextBoxColumn11.IsAutoGenerated = True
        GridViewTextBoxColumn11.Name = "Fax"
        Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate.Columns.AddRange(New Telerik.WinControls.UI.GridViewDataColumn() {GridViewTextBoxColumn1, GridViewTextBoxColumn2, GridViewTextBoxColumn3, GridViewTextBoxColumn4, GridViewTextBoxColumn5, GridViewTextBoxColumn6, GridViewTextBoxColumn7, GridViewTextBoxColumn8, GridViewTextBoxColumn9, GridViewTextBoxColumn10, GridViewTextBoxColumn11})
        Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate.DataSource = Me.CustomersBindingSource
        Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate.EnableGrouping = False
        Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate.ShowFilteringRow = False
        Me.RadMultiColumnComboBox1.EditorControl.Name = "NestedRadGridView"
        Me.RadMultiColumnComboBox1.EditorControl.ReadOnly = True
        Me.RadMultiColumnComboBox1.EditorControl.ShowGroupPanel = False
        Me.RadMultiColumnComboBox1.EditorControl.Size = New System.Drawing.Size(240, 150)
        Me.RadMultiColumnComboBox1.EditorControl.TabIndex = 0
        Me.RadMultiColumnComboBox1.Location = New System.Drawing.Point(13, 12)
        Me.RadMultiColumnComboBox1.Name = "RadMultiColumnComboBox1"
        Me.RadMultiColumnComboBox1.Size = New System.Drawing.Size(507, 21)
        Me.RadMultiColumnComboBox1.TabIndex = 0
        Me.RadMultiColumnComboBox1.TabStop = False
        Me.RadMultiColumnComboBox1.Text = "RadMultiColumnComboBox1"
        '
        'CustomersBindingSource
        '
        Me.CustomersBindingSource.DataMember = "Customers"
        Me.CustomersBindingSource.DataSource = Me.NwindDataSet
        '
        'NwindDataSet
        '
        Me.NwindDataSet.DataSetName = "NwindDataSet"
        Me.NwindDataSet.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        '
        'CustomersTableAdapter
        '
        Me.CustomersTableAdapter.ClearBeforeFill = True
        '
        'Form1
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(634, 406)
        Me.Controls.Add(Me.RadMultiColumnComboBox1)
        Me.Name = "Form1"
        Me.Text = "Form1"
        CType(Me.RadMultiColumnComboBox1.EditorControl.MasterTemplate, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.RadMultiColumnComboBox1.EditorControl, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.RadMultiColumnComboBox1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.CustomersBindingSource, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.NwindDataSet, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents RadMultiColumnComboBox1 As Telerik.WinControls.UI.RadMultiColumnComboBox
    Friend WithEvents NwindDataSet As MCCB_CustomFilteringVB.NwindDataSet
    Friend WithEvents CustomersBindingSource As System.Windows.Forms.BindingSource
    Friend WithEvents CustomersTableAdapter As MCCB_CustomFilteringVB.NwindDataSetTableAdapters.CustomersTableAdapter

End Class
