'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As Settings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")>  _
        Public ReadOnly Property HelpDeskPath() As String
            Get
                Return CType(Me("HelpDeskPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\Applications\Busines"& _ 
            "sGrid\Furniture.mdb;Persist Security Info=True")>  _
        Public ReadOnly Property FurnitureConnectionString() As String
            Get
                Return CType(Me("FurnitureConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\Applications\DataSou"& _ 
            "rces\Furniture.mdb;Persist Security Info=True")>  _
        Public ReadOnly Property FurnitureConnectionString1() As String
            Get
                Return CType(Me("FurnitureConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SalesDashBoard.png")>  _
        Public ReadOnly Property SalesDashboardImageLocation() As String
            Get
                Return CType(Me("SalesDashboardImageLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BookKiosk.png")>  _
        Public ReadOnly Property BookKioskImageLocation() As String
            Get
                Return CType(Me("BookKioskImageLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ScreenshotWinFormsQSF.png")>  _
        Public ReadOnly Property QSFImageLocation() As String
            Get
                Return CType(Me("QSFImageLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Helpdesk.png")>  _
        Public ReadOnly Property HelpDeskImageLocation() As String
            Get
                Return CType(Me("HelpDeskImageLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BugTracker.png")>  _
        Public ReadOnly Property BugTrackerImageLocation() As String
            Get
                Return CType(Me("BugTrackerImageLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PhotoAlbum.png")>  _
        Public ReadOnly Property PhotoAlbumImageLocation() As String
            Get
                Return CType(Me("PhotoAlbumImageLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("movieLab.png")>  _
        Public ReadOnly Property MovieLabImageLocation() As String
            Get
                Return CType(Me("MovieLabImageLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telerik Help Desk")>  _
        Public ReadOnly Property HelpDeskTitle() As String
            Get
                Return CType(Me("HelpDeskTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HelpDesk demo application for WinForms integrates components from Telerik UI for "& _ 
            "WinForms suite. It simulates a contact management system, which is data-bound to"& _ 
            " a Microsoft SQL Server to show how to build rich user interfaces with Telerik U"& _ 
            "I for WinForms. It illustrates how to combine our award-winning components to de"& _ 
            "liver elaborate UIs.")>  _
        Public ReadOnly Property HelpDeskDescription() As String
            Get
                Return CType(Me("HelpDeskDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telerik Movie Lab")>  _
        Public ReadOnly Property MovieLabTitle() As String
            Get
                Return CType(Me("MovieLabTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MovieLab demo application demonstrates the capabilities of RadListView for WinFor"& _ 
            "ms. Give your users slick and modern lists, kinetic scrolling, and hot tracking."& _ 
            " The features of RadListView at a glance.")>  _
        Public ReadOnly Property MovieLabDescription() As String
            Get
                Return CType(Me("MovieLabDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Bookstore Kiosk Demo")>  _
        Public ReadOnly Property BookstoreKioskTitle() As String
            Get
                Return CType(Me("BookstoreKioskTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("The Bookstore Kiosk Demo demonstrates the unmatched WPF-like visual attractivenes"& _ 
            "s of Telerik UIfor WinForms. It simulates a bookstore kiosk system, much like th"& _ 
            "e one you would use in your local bookstore. You can browse books, check for boo"& _ 
            "k availability, and even see the current book inventory through the Telerik Repo"& _ 
            "rting tool.")>  _
        Public ReadOnly Property BookstoreKioskDescription() As String
            Get
                Return CType(Me("BookstoreKioskDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Photo Gallery Example")>  _
        Public ReadOnly Property PhotoAlbumTitle() As String
            Get
                Return CType(Me("PhotoAlbumTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Similar to Bookstore Kiosk demo, this application demonstrates the unmatched WPF-"& _ 
            "like visual effects of Telerik UI for WinForms. It simulates a photo album viewe"& _ 
            "r that presents the photos using transitions. With the Telerik Presentation Fram"& _ 
            "ework that lies under Telerik UI for WinForms you can easily create cool transit"& _ 
            "ion effects.")>  _
        Public ReadOnly Property PhotoAlbumDescription() As String
            Get
                Return CType(Me("PhotoAlbumDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sales Dashboard")>  _
        Public ReadOnly Property SalesDashboardTitle() As String
            Get
                Return CType(Me("SalesDashboardTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("The Sales Dashboard for Windows Forms is a composite business application for vis"& _ 
            "ualizing a company’s sales force performance. It provides senior management with"& _ 
            " a dynamic application that enables monitoring and evaluation of enterprise sale"& _ 
            "s. By using statistical data representation, detailed information about individu"& _ 
            "al sales, tools for filtering data by various parameters it greatly facilitates "& _ 
            "the decision-making process in a classic business scenario.")>  _
        Public ReadOnly Property SalesDashBoardDescription() As String
            Get
                Return CType(Me("SalesDashBoardDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Demo Application")>  _
        Public ReadOnly Property QSFTitle() As String
            Get
                Return CType(Me("QSFTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("The Demo Application of Telerik UI WinForms showcases all Telerik WinForms contro"& _ 
            "ls in a single application. Each product comes with several examples, each with "& _ 
            "full source code.")>  _
        Public ReadOnly Property QSFDescription() As String
            Get
                Return CType(Me("QSFDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("The Bug Tracker demo is an excellent example of a real-world application that can"& _ 
            " be built with Telerik UI for WinForms. Thanks to the variety of navigation and "& _ 
            "data controls that this suite provides, you can easily set up a fully-functional"& _ 
            " application with a slick and finished look.")>  _
        Public ReadOnly Property BugTrackerDescription() As String
            Get
                Return CType(Me("BugTrackerDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\Controls\BusinessGri"& _ 
            "d\Furniture.mdb;Persist Security Info=True")>  _
        Public ReadOnly Property FurnitureConnectionString2() As String
            Get
                Return CType(Me("FurnitureConnectionString2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")>  _
        Public ReadOnly Property MovieLabPath() As String
            Get
                Return CType(Me("MovieLabPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/community/code-library/winforms/general/bugtracker-demo-ap"& _ 
            "plication.aspx")>  _
        Public ReadOnly Property BugTrackerPath() As String
            Get
                Return CType(Me("BugTrackerPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/support/code-library/photoalbum-demo-application")>  _
        Public ReadOnly Property PhotoAlbumPath() As String
            Get
                Return CType(Me("PhotoAlbumPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")>  _
        Public ReadOnly Property SalesDashboardPath() As String
            Get
                Return CType(Me("SalesDashboardPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BugTracker Demo Application")>  _
        Public ReadOnly Property BugTrackerTitle() As String
            Get
                Return CType(Me("BugTrackerTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")>  _
        Public ReadOnly Property BookstorePath() As String
            Get
                Return CType(Me("BookstorePath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public ReadOnly Property CarouselAnimationDelay() As Integer
            Get
                Return CType(Me("CarouselAnimationDelay"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public ReadOnly Property CarouselAnimationFrames() As Integer
            Get
                Return CType(Me("CarouselAnimationFrames"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("The File Explorer Demo emulates the UI representation of the Windows 8's File Exp"& _ 
            "lorer demonstrating that with Telerik UI for WinForms you can build application "& _ 
            "according to the latest fashion trends in the UI design.")>  _
        Public ReadOnly Property FileExplorerDescription() As String
            Get
                Return CType(Me("FileExplorerDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("fileExplorer.png")>  _
        Public ReadOnly Property FileExplorerImage() As String
            Get
                Return CType(Me("FileExplorerImage"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FileExplorer Demo Application")>  _
        Public ReadOnly Property FileExplorerTitle() As String
            Get
                Return CType(Me("FileExplorerTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FileExplorer Demo Application")>  _
        Public ReadOnly Property FileExplorerText() As String
            Get
                Return CType(Me("FileExplorerText"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telerik Checkers is an implementation of the standard Checkers game and follows m"& _ 
            "ost of its rules. The drag and drop restrictions and customizations are possible"& _ 
            " thanks to the capabilities of the RadDragDropService. This service allows you t"& _ 
            "o move a specific cell to a specific location, easily change the drag hint and h"& _ 
            "ave control over the data of the dragged cell and the target cell.")>  _
        Public ReadOnly Property CheckersDescription() As String
            Get
                Return CType(Me("CheckersDescription"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Checkers.png")>  _
        Public ReadOnly Property CheckersImage() As String
            Get
                Return CType(Me("CheckersImage"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telerik Checkers")>  _
        Public ReadOnly Property CheckersTitle() As String
            Get
                Return CType(Me("CheckersTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Telerik Checkers")>  _
        Public ReadOnly Property CheckersText() As String
            Get
                Return CType(Me("CheckersText"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms.aspx#DownloadableDemos")>  _
        Public ReadOnly Property QSFPath() As String
            Get
                Return CType(Me("QSFPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/community/code-library/winforms/gridview/telerik-checkers."& _ 
            "aspx")>  _
        Public ReadOnly Property CheckersPath() As String
            Get
                Return CType(Me("CheckersPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/community/code-library/winforms/general/fileexplorer-demo-"& _ 
            "application.aspx")>  _
        Public ReadOnly Property FileExplorerPath() As String
            Get
                Return CType(Me("FileExplorerPath"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.My.Settings
            Get
                Return Global.My.Settings.Default
            End Get
        End Property
    End Module
End Namespace
