//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPortfolio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")]
        public string HelpDeskPath {
            get {
                return ((string)(this["HelpDeskPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\Applications\\Busines" +
            "sGrid\\Furniture.mdb;Persist Security Info=True")]
        public string FurnitureConnectionString {
            get {
                return ((string)(this["FurnitureConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\Applications\\DataSou" +
            "rces\\Furniture.mdb;Persist Security Info=True")]
        public string FurnitureConnectionString1 {
            get {
                return ((string)(this["FurnitureConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.SalesDashBoard.png")]
        public string SalesDashboardImageLocation {
            get {
                return ((string)(this["SalesDashboardImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.BookKiosk.png")]
        public string BookKioskImageLocation {
            get {
                return ((string)(this["BookKioskImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.ScreenshotWinFormsQSF.png")]
        public string QSFImageLocation {
            get {
                return ((string)(this["QSFImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.Helpdesk.png")]
        public string HelpDeskImageLocation {
            get {
                return ((string)(this["HelpDeskImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.BugTracker.png")]
        public string BugTrackerImageLocation {
            get {
                return ((string)(this["BugTrackerImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.PhotoAlbum.png")]
        public string PhotoAlbumImageLocation {
            get {
                return ((string)(this["PhotoAlbumImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.movieLab.png")]
        public string MovieLabImageLocation {
            get {
                return ((string)(this["MovieLabImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Telerik Help Desk")]
        public string HelpDeskTitle {
            get {
                return ((string)(this["HelpDeskTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"HelpDesk demo application for WinForms integrates components from Telerik UI for WinForms suite. It simulates a contact management system, which is data-bound to a Microsoft SQL Server to show how to build rich user interfaces with Telerik UI for WinForms. It illustrates how to combine our award-winning components to deliver elaborate UIs.")]
        public string HelpDeskDescription {
            get {
                return ((string)(this["HelpDeskDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Telerik Movie Lab")]
        public string MovieLabTitle {
            get {
                return ((string)(this["MovieLabTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MovieLab demo application demonstrates the capabilities of RadListView for WinFor" +
            "ms. Give your users slick and modern lists, kinetic scrolling, and hot tracking." +
            " The features of RadListView at a glance.")]
        public string MovieLabDescription {
            get {
                return ((string)(this["MovieLabDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bookstore Kiosk Demo")]
        public string BookstoreKioskTitle {
            get {
                return ((string)(this["BookstoreKioskTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"The Bookstore Kiosk Demo demonstrates the unmatched WPF-like visual attractiveness of Telerik UI for WinForms. It simulates a bookstore kiosk system, much like the one you would use in your local bookstore. You can browse books, check for book availability, and even see the current book inventory through the Telerik Reporting tool.")]
        public string BookstoreKioskDescription {
            get {
                return ((string)(this["BookstoreKioskDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Photo Gallery Example")]
        public string PhotoAlbumTitle {
            get {
                return ((string)(this["PhotoAlbumTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Similar to Bookstore Kiosk demo, this application demonstrates the unmatched WPF-like visual effects of Telerik UI for WinForms. It simulates a photo album viewer that presents the photos using transitions. With the Telerik Presentation Framework that lies under Telerik UI for WinForms you can easily create cool transition effects.")]
        public string PhotoAlbumDescription {
            get {
                return ((string)(this["PhotoAlbumDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sales Dashboard")]
        public string SalesDashboardTitle {
            get {
                return ((string)(this["SalesDashboardTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"The Sales Dashboard for Windows Forms is a composite business application for visualizing a company’s sales force performance. It provides senior management with a dynamic application that enables monitoring and evaluation of enterprise sales. By using statistical data representation, detailed information about individual sales, tools for filtering data by various parameters it greatly facilitates the decision-making process in a classic business scenario.")]
        public string SalesDashBoardDescription {
            get {
                return ((string)(this["SalesDashBoardDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Demo Application")]
        public string QSFTitle {
            get {
                return ((string)(this["QSFTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Demo Application of Telerik UI for WinForms showcases all Telerik WinForms co" +
            "ntrols in a single application. Each product comes with several examples, each w" +
            "ith full source code.")]
        public string QSFDescription {
            get {
                return ((string)(this["QSFDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"The Bug Tracker demo is an excellent example of a real-world application that can be built with Telerik UI for WinForms. Thanks to the variety of navigation and data controls that this suite provides, you can easily set up a fully-functional application with a slick and finished look.")]
        public string BugTrackerDescription {
            get {
                return ((string)(this["BugTrackerDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\Controls\\BusinessGri" +
            "d\\Furniture.mdb;Persist Security Info=True")]
        public string FurnitureConnectionString2 {
            get {
                return ((string)(this["FurnitureConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")]
        public string MovieLabPath {
            get {
                return ((string)(this["MovieLabPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/community/code-library/winforms/general/bugtracker-demo-ap" +
            "plication.aspx")]
        public string BugTrackerPath {
            get {
                return ((string)(this["BugTrackerPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")]
        public string PhotoAlbumPath {
            get {
                return ((string)(this["PhotoAlbumPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/community/labs/sales-dashboard-for-winforms.aspx")]
        public string SalesDashboardPath {
            get {
                return ((string)(this["SalesDashboardPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BugTracker Demo Application")]
        public string BugTrackerTitle {
            get {
                return ((string)(this["BugTrackerTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")]
        public string BookstorePath {
            get {
                return ((string)(this["BookstorePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int CarouselAnimationDelay {
            get {
                return ((int)(this["CarouselAnimationDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int CarouselAnimationFrames {
            get {
                return ((int)(this["CarouselAnimationFrames"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The File Explorer Demo emulates the UI representation of the Windows 8\'s File Exp" +
            "lorer demonstrating that with Telerik UI for WinForms you can build application " +
            "according to the latest fashion trends in the UI design.")]
        public string FileExplorerDescription {
            get {
                return ((string)(this["FileExplorerDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.fileExplorer.png")]
        public string FileExplorerImage {
            get {
                return ((string)(this["FileExplorerImage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FileExplorer Demo Application")]
        public string FileExplorerTitle {
            get {
                return ((string)(this["FileExplorerTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FileExplorer Demo Application")]
        public string FileExplorerText {
            get {
                return ((string)(this["FileExplorerText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Telerik Checkers is an implementation of the standard Checkers game and follows most of its rules. The drag and drop restrictions and customizations are possible thanks to the capabilities of the RadDragDropService. This service allows you to move a specific cell to a specific location, easily change the drag hint and have control over the data of the dragged cell and the target cell.")]
        public string CheckersDescription {
            get {
                return ((string)(this["CheckersDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppPortfolio.Resources.Checkers.png")]
        public string CheckersImage {
            get {
                return ((string)(this["CheckersImage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Telerik Checkers")]
        public string CheckersTitle {
            get {
                return ((string)(this["CheckersTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Telerik Checkers")]
        public string CheckersText {
            get {
                return ((string)(this["CheckersText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/products/winforms/sample-applications.aspx")]
        public string QSFPath {
            get {
                return ((string)(this["QSFPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/community/code-library/winforms/gridview/telerik-checkers." +
            "aspx")]
        public string CheckersPath {
            get {
                return ((string)(this["CheckersPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.telerik.com/community/code-library/winforms/general/fileexplorer-demo-" +
            "application.aspx")]
        public string FileExplorerPath {
            get {
                return ((string)(this["FileExplorerPath"]));
            }
        }
    }
}
